"""empty message

Revision ID: 15ffcfd6bf70
Revises: d9cab9c2f101
Create Date: 2020-01-21 19:33:11.115261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ffcfd6bf70'
down_revision = 'd9cab9c2f101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_user_name', table_name='users')
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.create_index('ix_users_user_name', 'users', ['user_name'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###
