"""Add followers and followed.

Revision ID: 95076d40357c
Revises: 15ffcfd6bf70
Create Date: 2020-01-21 21:28:12.365463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95076d40357c'
down_revision = '15ffcfd6bf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('followed_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
